project: 
  type: website
  
website: 
  title: Mental Health Epidemiology Group
  page-navigation: true
  navbar: 
    logo: "identidade_visual/png/logo_color_transp.png"
    left: 
      - index.qmd
      - courses.qmd
      - publications.qmd
      - resources.qmd
      - team.qmd
      - contact.qmd
  favicon: "identidade_visual/png/logo_color_transp.png"
  page-footer: "Mental Health Epidemiology Group - 2024"
theme: flatly
format: 
  html: 
    css: style.css