---
title: "Mental Health Epidemiology Group"
format: html
editor: visual
---

# Who We Are

The Mental Health Epidemiology Group is a dedicated research team based at the [Federal University of Santa Maria](https://www.ufsm.br/). Our passion lies in the field of psychiatric epidemiology, nosology, and psychometrics. At our core, we aim to deepen our understanding of mental health patterns, influences, and outcomes through comprehensive research and disseminate this knowledge to students, professionals, and the wider community through educational courses. By bridging the gap between research and practice, we strive to make a positive impact on mental health policies and interventions in Brazil and beyond.

## Research Areas

We delve into a wide range of research areas that have significant implications for mental health and well-being. Our primary research focuses include:

### Psychiatric Epidemiology

Exploring the prevalence, incidence, risk factors, and distribution of mental disorders in populations to inform public health strategies.

### Nosology

Investigating the classification and categorization of mental disorders.

### Psychometrics

Developing and validating reliable measurement tools to assess mental health constructs and aid in accurate data collection.

## What We Do

### Research

Our team of researchers conducts studies that contribute to the scientific understanding of mental health phenomena. By employing rigorous methodologies and innovative approaches, we seek to advance knowledge in the field.

### Courses

As part of our commitment to knowledge dissemination, we offer specialized courses on mental health epidemiology, nosology, and psychometrics. These courses cater to students, academics, mental health professionals, and anyone interested in gaining expertise in these areas.

### Tools

In addition to our research and courses, we are dedicated to developing tools that assist researchers and clinicians in their endeavors related to various aspects of mental health.

## Get Involved

We welcome individuals who share our passion for mental health research and advocacy to join us in our endeavors. Whether you are a student, researcher, or practitioner, there are opportunities for collaboration, participation in our courses, and contributing to meaningful research.

## Contact Us

If you have any inquiries, want to collaborate, or seek more information about our research group and courses, please feel free to get in touch with us:

Email: [**joaopgp123\@gmail.com**](mailto:joaopgp123@gmail.com)

Thank you for visiting our website.
