---
title: "Publications"
format: html
editor: visual
---

**Researcher Profiles**

-   **Prof. Dr. Maurício Scopel Hoffmann**

    -   [Google Scholar Profile](https://scholar.google.com.br/citations?user=5TpABw4AAAAJ&hl=pt-BR)

-   **Prof. MSc. João Pedro Gonçalves Pacheco**

    -   [Google Scholar Profile](https://scholar.google.com.br/citations?user=WKB1RRkAAAAJ&hl=pt-BR)

**Featured Publications:**

1.  [A general psychopathology factor (P factor) in children: Structural model analysis and external validation through familial risk and child global executive function.](https://psycnet.apa.org/record/2016-49574-001)
    -   Year: 2017
    -   Published in: Journal of Abnormal Psychology
2.  [Effects of mental health status during adolescence on primary care costs in adulthood across three British cohorts](https://link.springer.com/article/10.1007/s00127-023-02507-y)
    -   Year: 2023
    -   Published in: Social Psychiatry and Psychiatric Epidemiology
3.  [Parent- and teacher-reported associations from adolescent bifactor models of psychopathology: an outcome-wide association study of 26 outcomes in mid-life](https://acamh.onlinelibrary.wiley.com/doi/abs/10.1111/jcpp.13707)
    -   Year: 2022
    -   Published in: Journal of Child Psychology and Psychiatry
4.  [Reliability and validity of bifactor models of dimensional psychopathology in youth](https://psycnet.apa.org/record/2022-58765-003)
    -   Year: 2022
    -   Published in: Journal of Psychopathology and Clinical Science
5.  [Translating measurement into practice: Brazilian norms for depressive symptom assessment with the Patient Health Questionnaire (PHQ-9)](https://www.scielo.br/j/rbp/a/sbXWVsDYFPZwnx449xzChTL/?lang=en)
    -   Year: 2023
    -   Published in: Brazilian Journal of Psychiatry
6.  [Estimated Prevalence of Perinatal Depression in Low- and Middle-Income Countries Considering Uncertainty of Test Properties](https://jamanetwork.com/journals/jamapsychiatry/article-abstract/2806609)
    -   Year: 2023
    -   Published in: JAMA Psychiatry
7.  [Translation, cultural adaptation, and validation of the Brazilian Portuguese version of the Higher Education Stress Inventory (HESI-Br)](https://pubmed.ncbi.nlm.nih.gov/35507827/)
    -   Year: 2022
    -   Published in: Trends in Psychiatry and Psychotherapy
8.  [Prevalence of depressive symptoms among medical students: overview of systematic reviews](https://onlinelibrary.wiley.com/doi/abs/10.1111/medu.13770)
    -   Year: 2019
    -   Published in: Medical Education
9.  [Mental health problems among medical students in Brazil: a systematic review and meta-analysis](https://www.scielo.br/j/rbp/a/FsKx7VwgRVSvwS638BqhbmK/)
    -   Year: 2017
    -   Published in: Brazilian Journal of Psychiatry
10. [Gender inequality and depression among medical students: A global meta-regression analysis](https://www.sciencedirect.com/science/article/abs/pii/S0022395618310586)
    -   Year: 2019
    -   Published in: Journal of Psychiatric Research

Please note that this list is not exhaustive, and our researchers have contributed other valuable publications. You can explore their complete publication records through their respective Google Scholar profiles.

For any inquiries regarding our research, please don't hesitate to contact us.
