---
title: "Resources"
format: html
editor: visual
---

# Harmony

If you are a researcher in need of harmonizing and comparing questionnaires, check out [Harmony](https://harmonydata.ac.uk/)! This valuable tool can save you time and enhance the quality of your research. It is being developed by a collaborative team from the UK and Brazil (Dr. Hoffmann), and is funded by the Wellcome Trust (Data Prize).

See how it works:

<https://www.youtube.com/watch?v=cEZppTBj1NI&ab_channel=Harmony>

# DSM-XC Calculator

The DSM Level 1 Cross-Cutting Symptom Measure (DSM-XC) (<https://www.psychiatry.org/getmedia/e0b4b299-95b3-407b-b8c2-caa871ca218d/APA-DSM5TR-Level1MeasureAdult.pdf)> calculator allows for visualizing the change from the pre- to the post-test probability of 8 mental disorders. The user can select from the multiple psychopathological domains the DSM-XC measures, the adverbial framing that was used and if the test was positive or negative. The acompanying paper is currently under review. Estimates are based on the latest assessment of 22 years old of the 1993 Pelotas Birth Cohort.

<https://pacheco-jpg.shinyapps.io/dsm_xc_shiny_app/>

# PHQ-9 Calculator

The Patient Health Questionnaire-9 calculator, developed by our team, computes your standardized depression score, compared with the Brazilian population.The standardized score (T Score) is a measure that uses a method called Item Response Theory, based on the analyses of answers to the same questions by Brazilians in the National Health Survey of 2019 (Damiano et al. 2023 - https://doi.org/10.47626/1516-4446-2022-2945). This standardized score ranges from 0 to 100, with 0 to 50 representing no symptoms, 50 to 60 representing a few symptoms, between 60 and 70 as moderate symptoms, and above 70 as severe symptoms that warrant clinical attention for depression.

<https://mheg.shinyapps.io/phq9-score/>

# SMFQ Calculator

The Short Mood and Feelings Questionnaire Calculator was developed to estimate post-test probabilities for psychiatric conditions within the internalizing spectrum. Using data from the Brazilian High-Risk Cohort Study (2018–2019; Salum et al., 2015; <https://doi.org/10.1002/mpr.1459),> this tool allows clinicians to input SMFQ responses and generate T-scores based on Item Response Theory (IRT) parameters. Pre-test probability (prevalence) estimates, weighted for the study’s oversampling procedure, are then combined with interval likelihood ratios (ILRs) to refine post-test probability calculations, offering greater predictive accuracy than traditional dichotomous likelihood ratios. The tool also enables pre-test parameter adjustments, making it adaptable to diverse populations with comparable characteristics.

The calculator is available in American English (<https://mheg.shinyapps.io/mfq-score-en/)> and Brazilian Portuguese (<https://mheg.shinyapps.io/mfq-score-main/).>
